services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=chat-space
    env_file:
      - .env

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    environment:
      - redis-server --appendonly yes
    volumes:
      - "redis-data:/data"

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  rabbitmq-data:
    driver: local
